src/app/layouts/PageLayout/Header/NetworkSelect.tsx
src/app/templates/ExploreAccount.tsx
src/app/templates/OperationHistory.tsx
src/lib/thanos/back.ts
src/lib/thanos/front.ts
src/lib/thanos/networks.ts
src/lib/thanos/types.ts
src/lib/tzstats.ts

Also Rename module filename: `TZStatsAPI` -> `tzstats` (Not React Component or other PascalCase stuff)

Implement dynamic & persistent Network system

---

src/app/templates/OperationHistory.tsx
src/background.ts
src/lib/intercom/client.ts
src/lib/intercom/index.ts
src/lib/intercom/server.ts
src/lib/thanos/back.ts
src/lib/thanos/back/actions.ts
src/lib/thanos/back/store.ts
src/lib/thanos/front.ts

- Fix React error in `OperationHistory.tsx`;
- Improve `Intercom` logic: make it friendly for multiple handlers;
- Integrate `Intercom` for both sides: front & back;
- Decompose `store` and `actions` from ThanosBack(`lib/thanos/back.ts`);
- Refactor ThanosBack(`lib/thanos/back.ts`).

Feat integrate intercom

---

src/app/templates/DAppSettings.tsx
src/lib/thanos/back/actions.ts
src/lib/thanos/back/dapp.ts
src/lib/thanos/back/vault.ts
src/lib/thanos/types.ts

Fix: reimplement dapp session storage

---

src/app/ConfirmPage.tsx
src/app/atoms/Alert.tsx
src/app/templates/InternalConfiramtion.tsx
tailwind.config.js

Don't worry, this error was created temporarily just for testing

Improve make alerts closable

---

src/app/templates/RevealSecret.tsx

For purposes of this demo, here https://github.com/madfish-solutions/thanos-wallet/pull/125/files#diff-302f5fca3ca2e89c2dc2cb28611722faR213 `ThanosAccountType.Ledger` was temporarily replaced with `ThanosAccountType.HD`

Disallow private key revealling for Ledger accounts

---

public/_locales/en/messages.json
public/_locales/ru/messages.json
src/app/layouts/PageLayout/Header.tsx
src/app/layouts/PageLayout/Header/AccountDropdown.tsx
src/app/layouts/PageLayout/Header/LanguageSelect.tsx
src/app/pages/CreateAccount.tsx
src/app/templates/About.tsx
src/app/templates/ActivateAccount.tsx
src/app/templates/AdditionalFeeInput.tsx
src/app/templates/AssetSelect.tsx
src/app/templates/BackupSeedAlert.tsx
src/app/templates/BakerBanner.tsx
src/app/templates/CustomNetworksSettings.tsx
src/app/templates/DAppSettings.tsx
src/app/templates/DelegateForm.tsx
src/app/templates/InternalConfiramtion.tsx
src/app/templates/NetworkBanner.tsx
src/app/templates/NewWallet.tsx
src/app/templates/OperationHistory.tsx
src/app/templates/OperationStatus.tsx
src/app/templates/OperationsBanner.tsx
src/app/templates/RemoveAccount.tsx
src/app/templates/RevealSecret.tsx
src/app/templates/SendForm.tsx
src/lib/i18n.ts
src/lib/thanos/assets.ts
src/lib/thanos/types.ts
src/lib/ui/i18n.tsx

Feat switching languages

---

public/_locales/en/messages.json
src/app/templates/IconifiedSelect.tsx
src/app/templates/LocaleSelect.tsx
src/app/templates/PopupSettings.tsx

Improve update general settings

---

public/_locales/en/messages.json
src/app/templates/DAppLogo.tsx
src/app/templates/DAppSettings.tsx

DApps list: design updates

---

src/app/templates/CustomNetworksSettings.tsx
src/app/templates/ManagedKTForm.tsx
src/app/templates/OperationHistory.tsx
src/app/templates/OperationStatus.tsx
src/lib/better-call-dev/client.ts
src/lib/better-call-dev/types.ts
src/lib/thanos/types.ts
src/lib/tzkt/client.ts
src/lib/tzstats/client.ts

Add request to BCD API

---

public/_locales/en/messages.json
src/app/pages/AddToken.tsx
src/lib/thanos/assets.ts

Minor bugfixes

---

src/app/templates/OperationHistory.tsx
src/lib/thanos/assets.ts

Fix additional tokens fixtures

---

src/app/atoms/FormField.tsx
src/app/pages/Explore/AddressChip.tsx
src/app/pages/Receive.tsx
src/app/templates/ViewsSwitcher.tsx

Add displaying domain name on 'Receive' page

---

src/lib/thanos/assets.ts

Howdy friends, we deployed another version of our FA1.2 contract so we need to update things here as well!

Update token contract after re-deploy

---

public/_locales/en/messages.json
src/app/atoms/Money.tsx
src/app/icons/chevron-up.svg
src/app/templates/InUSD.tsx
src/app/templates/SendForm.tsx

Implement toggling XTZ/USD in 'Send' form

---

public/_locales/en/messages.json
src/app/pages/ImportAccount.tsx

Faucet import updates

---

src/app/templates/OperationsBanner.tsx
src/lib/thanos/back/dapp.ts
src/lib/thanos/front/expenses.ts

Payload: `0x05010000004254657a6f73205369676e6564204d6573736167653a206d79646170702e636f6d20323032312d30312d31345431353a31363a30345a2048656c6c6f20776f726c6421`

Implement message signing

---

public/_locales/en/messages.json

Minor changes to the default `en` locale

Message wording improvements

---

public/_locales/en/messages.json

Minor locale improvements

---

src/app/ConfirmPage.tsx
src/app/pages/Explore/AddUnknownTokens.tsx
src/app/templates/ExpensesView.tsx
src/app/templates/InUSD.tsx
src/app/templates/InternalConfiramtion.tsx
src/app/templates/OperationView.tsx
src/app/templates/SendForm.tsx
src/lib/temple/front/usdprice.ts

Implement Total Fee on Confirm Page

---

public/_locales/en/messages.json
src/app/pages/Explore/AddressChip.tsx
src/app/templates/BakerBanner.tsx
src/app/templates/DelegateForm.tsx

Implement inputting domains in delegation form

---

src/app/ConfirmPage.tsx
src/app/layouts/PageLayout/ConfirmationOverlay.tsx
src/app/templates/ExpensesView.tsx
src/app/templates/IncreaseStorageFeeSection.tsx
src/app/templates/InternalConfirmation.tsx
src/app/templates/OperationView.tsx
src/app/templates/RawPayloadView.tsx
src/lib/temple/back/actions.ts
src/lib/temple/back/dapp.ts
src/lib/temple/back/dryrun.ts
src/lib/temple/defaults.ts
src/lib/temple/front/client.ts
src/lib/temple/front/index.ts
src/lib/temple/types.ts

Storage fee increase

---

public/manifest.json

Fixed failing requests to Better Call Dev API

---

src/app/templates/CustomNetworksSettings.tsx

Fix displaying error for getting chain id

---

src/lib/temple/assets.ts

Greetings from Hover Labs! We're rolling out a new feature for Kolibri which contains a token. 
This PR adds a new token, **Q**uipuswap **L**iquidating **kUSD**. 
This token is an LP tokens for users participating in the [Kolibri Liquidity Pool](https://kolibri-xtz.medium.com/new-initiatives-for-kusd-3b67e3ec26fa). We'd like tokens for such users to show up automatically in Thanos.

Add QLkUSD Token

---

src/app/templates/ExpensesView.tsx
src/app/templates/Operation.tsx

Fix transaction confirmation for large transactions

---

public/_locales/en/messages.json
src/app/templates/ModifyStorageLimitSection.tsx

Change storageLimit editable field size and wording

---

public/_locales/en/messages.json
public/manifest.json
src/app/pages/ConnectLedger.tsx
src/lib/better-call-dev/base.ts
src/lib/temple/back/actions.ts
src/lib/temple/back/main.ts
src/lib/temple/back/vault.ts
src/lib/temple/front/client.ts
src/lib/temple/types.ts

Add 'Derivation type' field for ledger connection

---

public/_locales/en/messages.json
src/app/templates/SendForm.tsx
src/lib/temple/front/address-book.ts
src/lib/temple/front/index.ts

Added 'Recent destinations' section to 'Send' form

---

public/_locales/en/messages.json
public/_locales/en_GB/messages.json
public/_locales/fr/messages.json
public/_locales/ja/messages.json
public/_locales/ko/messages.json
public/_locales/uk/messages.json
public/_locales/zh_CN/messages.json
public/_locales/zh_TW/messages.json
src/app/templates/InUSD.tsx
src/app/templates/SendForm.tsx
src/lib/better-call-dev/base.ts
src/lib/makeBuildQueryFn.ts
src/lib/temple/front/usdprice.ts
src/lib/temple/helpers.ts
src/lib/templewallet-api/index.ts
src/lib/templewallet-api/operations.ts
src/lib/templewallet-api/types.ts

Add USD equivalent for tokens

---

src/app/templates/SwapForm/SwapInput.tsx

Swap form: change dropdown height

---

src/app/templates/InternalConfirmation.tsx

https://user-images.githubusercontent.com/10885399/119948693-c2933800-bfa1-11eb-9171-32c9666c4c37.mp4

Internal confirmation: fix finding FA2 token which is sent

---

src/app/templates/SwapForm.tsx
src/app/templates/SwapForm/SwapInput.tsx

Swap form: minor UI updates

---

src/app/PageRouter.tsx
src/app/pages/Explore.tsx
src/app/pages/Swap.tsx
src/app/templates/SwapForm.tsx
src/app/templates/SwapForm/useSwappableAssets.ts
src/lib/analytics/use-page-router-analytics.hook.ts
src/lib/temple/front/swap.ts

https://user-images.githubusercontent.com/10885399/121012459-677ef380-c7a0-11eb-870b-4e1666fd5c08.mp4

'Swap' form: fix Kalamint exchanging + implement selecting another initial asset than TEZ

---

src/app/templates/SwapForm.tsx
src/app/templates/SwapForm/SwapInput.tsx
src/app/templates/SwapForm/useSwappableAssets.ts

Reverts madfish-solutions/templewallet-extension#357

Revert "Swap form: fix initial selection of non-whitelisted assets + fix toke…"

---

src/app/pages/Swap.tsx

Make 'Swap' form frame visible while loading

---

src/app/templates/RevealSecret.tsx

Limit time of revealing the Mnemonics / Private key on screen, [Crypto]A-004

updated timeout for reveal mnemonic phrase

---

public/_locales/de/messages.json
public/_locales/en/messages.json
public/_locales/en_GB/messages.json
public/_locales/fr/messages.json
public/_locales/ja/messages.json
public/_locales/ko/messages.json
public/_locales/pt/messages.json
public/_locales/tr/messages.json
public/_locales/uk/messages.json
public/_locales/zh_CN/messages.json
public/_locales/zh_TW/messages.json
src/app/layouts/PageLayout/Header/AccountDropdown.tsx

No functionality to "logout" from wallet (delete current wallet), D-008

More convenient lock label

---

src/lib/analytics/use-analytics-settings.hook.ts

Extension collect analytics without user consent, [CRYPTO] A-007

Removed analytics tracking

---

public/manifest.json
src/app/defaults.tsx
src/lib/temple/networks.ts

changed http to https

---

src/app/atoms/FormField.tsx
src/app/templates/RevealSecret.tsx

- 30 sec for reveal
- 3 mins for password

Reveal secret timeout

---

xcode/Temple Extension/SafariWebExtensionHandler.swift

Leaking log message in Safari, A-014

Safari log fix

---

src/app/templates/NewWallet.tsx
src/app/templates/NewWallet/Verify.tsx
src/app/templates/RevealSecret.tsx
src/lib/temple/front/client.ts

"seed_revealed" is never false, A-011

Removed unused state "seed revealed"

---

src/lib/temple/back/vault.ts

"vault_check" value is null during encryption, C-005

Vaul check phrase

---

src/contentScript.ts

Restrict origin of postMessages for content scripts, A-005

Restriction for contentScript message sending

---

public/_locales/en/messages.json
public/_locales/en_GB/messages.json
src/app/pages/Unlock.tsx
src/lib/temple/types.ts

Lack of brute-force countermeasures for user password, A-006

Bruteforce prevention

---

.prettierrc.js
src/app/templates/NewWallet.tsx
src/lib/popup-mode/index.ts
src/lib/temple/back/vault.ts
src/lib/temple/reset.ts
src/options.tsx

Shared extension settings among different wallets, P-004

Unset settings on logout

---

public/_locales/de/messages.json
public/_locales/pt/messages.json

Crush when installing extention on Portugal. Turkish. German

Locales fix (Portugal, German)

---

src/app/templates/NewWallet.tsx
src/app/templates/NewWallet/Verify.tsx

Seed phrase collisions

---

public/_locales/en/messages.json
public/_locales/en_GB/messages.json
src/app/pages/Unlock.tsx

Reverts madfish-solutions/templewallet-extension#448

Revert "Bruteforce prevention fixes"

---

public/_locales/en/messages.json
public/_locales/en_GB/messages.json
src/app/pages/Unlock.tsx

Reverts madfish-solutions/templewallet-extension#452

Bruteforce prevention fixes

---

public/_locales/de/messages.json

Correct german ledger translation. Also in german language a Ledger is a Ledger

Correct german ledger translation

---

public/_locales/en/messages.json

attentionDescription message hotfix

---

src/app/layouts/PageLayout/Header/AccountDropdown.tsx
src/app/pages/BuyCrypto/BuyCryptoInput.tsx
src/app/pages/BuyCrypto/CurrencyComponent.tsx
src/app/pages/BuyCrypto/steps/ErrorComponent.tsx
src/app/pages/BuyCrypto/steps/ExchangeStep.tsx
src/app/pages/BuyCrypto/steps/InitialStep.tsx
src/app/pages/BuyCrypto/steps/WarningComponent.tsx
src/app/pages/Collectibles/CollectiblesList.tsx

Reverts madfish-solutions/templewallet-extension#464

Revert "Sonarqube fixes #3"

---

src/app/layouts/PageLayout/Header/AccountDropdown.tsx
src/app/pages/BuyCrypto/BuyCryptoInput.tsx
src/app/pages/BuyCrypto/CurrencyComponent.tsx
src/app/pages/BuyCrypto/steps/ErrorComponent.tsx
src/app/pages/BuyCrypto/steps/ExchangeStep.tsx
src/app/pages/BuyCrypto/steps/InitialStep.tsx
src/app/pages/BuyCrypto/steps/WarningComponent.tsx
src/app/pages/Collectibles/CollectiblesList.tsx

This reverts commit 1caece040c34f5fc2aa13313b86096d37f4a2a5a.

Revert "Revert "Sonarqube fixes #3 (#464)" (#478)"

---

src/app/pages/Explore/BakingSection.tsx

Reverts madfish-solutions/templewallet-extension#508

Revert "Delegation → welcome page - improvement"

---

src/app/pages/Send.tsx

Reverts madfish-solutions/templewallet-extension#510

Revert "Send asset switch when account changes"

---

src/app/pages/Explore/Tokens.module.css
src/app/templates/CustomNetworksSettings.tsx
src/app/templates/CustomSelect.tsx
src/app/templates/DAppSettings.tsx
src/app/templates/DelegateForm.tsx
src/app/templates/InUSD.tsx
src/lib/temple/front/baking.ts

Reverts madfish-solutions/templewallet-extension#481

Revert "Sonarqube fixes #6"

---

src/app/pages/Explore/Tokens.module.css
src/app/templates/CustomNetworksSettings.tsx
src/app/templates/CustomSelect.tsx
src/app/templates/DAppSettings.tsx
src/app/templates/DelegateForm.tsx
src/app/templates/InUSD.tsx
src/lib/temple/front/baking.ts

Reverts madfish-solutions/templewallet-extension#515

Revert "Revert "Sonarqube fixes #6""

---

src/app/pages/Send.tsx

Reverts madfish-solutions/templewallet-extension#514

Revert "Revert "Send asset switch when account changes""

---

src/app/pages/Explore/BakingSection.tsx

Reverts madfish-solutions/templewallet-extension#513

Revert "Revert "Delegation → welcome page - improvement""

---

src/app/pages/Explore/MainBanner.tsx

Token name overrides token image in collapsed view

---

public/_locales/de/messages.json

Renamed more german word "Hauptbuch" to Ledger

Renamed more german word "Hauptbuch" to Ledger

---

src/lib/temple/beacon.mock.ts
src/lib/temple/beacon.test.ts
src/lib/temple/beacon.ts
src/lib/temple/libsodium-wrappers.mock.ts
src/lib/temple/sodium.mock.ts

CQ-002: Lack of proper testing of beacon-related cryptographic code

Beacon security test

---

src/background.ts

Lock up fix

---

src/app/defaults.tsx

CQ-004 
https://www.notion.so/madfissolutions/Fix-CQ-004-audit-issue-7148f1403dbd404380d2892900744cb9

Fix url matching

---

public/_locales/uk/messages.json

https://www.notion.so/madfissolutions/Localization-duplicate-4a7da133512d4fffbf1af0cc7baa38f8

Remove UA locale artifact

---

src/app/templates/SwapForm/SwapForm.form.tsx

https://www.notion.so/madfissolutions/swap-section-set-TEZ-in-input-b5919b7f23b94557adbf0c254c313ab4

Swap default input asset

---

src/app/icons/swap.svg

https://www.notion.so/madfissolutions/Different-thickness-of-lines-of-icons-297426755de946ef9b47e9592e198d1a

Explore bar icons fix

---

src/app/atoms/CopyButton.tsx
src/app/pages/BuyCrypto/BuyCrypto.selectors.ts
src/app/pages/BuyCrypto/BuyCrypto.tsx
src/app/pages/BuyCrypto/steps/ApproveStep.tsx
src/app/pages/BuyCrypto/steps/ErrorComponent.tsx
src/app/pages/BuyCrypto/steps/ExchangeStep.tsx
src/app/pages/BuyCrypto/steps/InitialStep.tsx
src/app/pages/SelectCrypto/Cryptos.tsx
src/app/pages/SelectCrypto/SelectCrypto.selectors.ts

https://www.notion.so/madfissolutions/Amplitude-update-top-up-events-cba98c24be8146319f51047a2f6cf993

Topup analytics

---

src/app/icons/swap-header.svg
src/app/pages/Swap/Swap.tsx

https://www.notion.so/madfissolutions/Swap-icon-in-Swap-section-is-not-rendered-6df72619e2b4405ab92fcea37ef5a0b3

Swap icon in header

---

package.json
yarn.lock

https://www.notion.so/madfissolutions/Fix-postcss-plugin-was-deprecated-warning-8f8f21d57c2645a2b8c9e8d536b01e04

Postcss-7 deprecation warning

---

src/app/pages/Settings.tsx

https://www.notion.so/madfissolutions/Make-whole-settings-tab-clickable-07907f1a6ff941d3af0cf280dd8b3f9f

Clickable settings tab

---

src/app/templates/DAppsList.tsx
src/app/templates/DAppsList/DAppIcon.tsx
src/app/templates/DAppsList/DAppItem.tsx
src/lib/custom-dapps-api/types.ts

https://www.notion.so/madfissolutions/Development-05abe2b65cd14ae39a101533bc01b708?p=2984d44f213d4bc4b79a75903ff3627b

add hardcoded dapp list

---

README.md
public/fullpage.html
public/manifest.json
public/popup.html
src/contentScript.ts
src/lib/temple/beacon.ts

https://www.notion.so/madfissolutions/Delete-Thanos-from-the-app-a17257a855ab45ae83be986bc2b306c6

Rename Thanos to Temple

---

src/lib/temple/front/blockexplorer.ts

https://www.notion.so/madfissolutions/Add-block-explorer-to-Ithaca-net-8e164e65a2c84ed7a96827c7a5c8f495

Ithaca explorer

---

src/lib/temple/networks.ts

https://www.notion.so/madfissolutions/The-smartpy-ithacanet-node-is-showing-as-unknown-in-temple-wallet-e600286bb1584a788a8b7f0a8cad9b68

Added ithaca smartpy RPC

---

src/app/atoms/Name.tsx
src/app/pages/Explore/Tokens.module.css
src/app/pages/Explore/Tokens.tsx
src/app/pages/ManageAssets.module.css
src/app/pages/ManageAssets.tsx

https://www.notion.so/madfissolutions/A-price-value-is-out-of-frame-after-editing-a-token-s-name-after-appearing-truncate-e20c8d66bd8c4d4089710e34dae1df0c

Long asset name or price

---

src/app/layouts/PageLayout/Header/AccountDropdown.tsx

https://www.notion.so/madfissolutions/Add-scroll-bar-in-Accounts-list-557cde725a9d4434bbc6e2ecf72d6f43

Account list scroll

---

src/app/pages/BuyCrypto/BuyCrypto.tsx
src/app/pages/BuyCrypto/config.ts
src/app/pages/BuyCrypto/steps/ApproveStep.tsx
src/app/pages/BuyCrypto/steps/ErrorComponent.tsx
src/app/pages/BuyCrypto/steps/ExchangeStep.tsx
src/app/pages/BuyCrypto/steps/InitialStep.tsx
src/app/pages/BuyCrypto/steps/WarningComponent.tsx
src/app/pages/BuyCrypto/utils/useTopUpUpdate.tsx

https://www.notion.so/madfissolutions/exolix-improvement-f8901de630b44cdb8f02d498239ba7db

Exolix improvement

---

src/lib/better-call-dev/base.ts
src/lib/tzkt/client.ts

https://www.notion.so/madfissolutions/Non-Fungible-tokens-transfers-not-showing-correctly-on-Ithacanet-and-when-manually-adding-they-show-80366d26166b41bca8f81c088d037e2f

Nun-fungible tokens on ithacanet

---

src/app/templates/NewWallet.tsx

https://www.notion.so/madfissolutions/If-user-use-File-Password-kukai-as-Extension-password-does-not-appear-notification-that-password-f-4dbb30c660184aa7bf9daa910610b719

Keystore password requirements

---

src/app/ConfirmPage.tsx
src/app/templates/ConnectBanner.tsx
src/app/templates/DAppLogo.tsx
src/lib/temple/back/actions.ts
src/lib/temple/back/dapp.ts
src/lib/temple/types.ts

https://www.notion.so/madfissolutions/Beacon-bugs-78ffa470197b4a288ffb23aee59212d8

Beacon DApps bad URL

---

src/app/pages/AddAsset.tsx

https://www.notion.so/madfissolutions/Development-05abe2b65cd14ae39a101533bc01b708?p=7b5bbc4b090e4114a37cccabb28696ab

Add asset form clear if metadata failed to load

---

src/lib/better-call-dev/base.ts
src/lib/temple/beacon.ts
src/lib/temple/front/blockexplorer.ts
src/lib/temple/networks.ts
src/lib/temple/types.ts
src/lib/tzkt/client.ts

Remove hangzhou

---

src/lib/temple/activity/sync.ts
src/lib/tzkt/client.ts

https://www.notion.so/madfissolutions/Transactions-FA-1-2-FA2-SWAP-Delegation-are-not-shown-on-the-Activity-page-on-the-recipient-s-6ba09d41286e495d9eb9b74a10e49fa6

Added track of incoming transactions

---

src/app/templates/AssetIcon.tsx
src/lib/image-uri.ts

https://www.notion.so/madfissolutions/NFT-icon-shows-a-black-circle-instead-of-an-image-bc5809c2ed4c42f38ac3c161505c28d3

Asset icon fallback

---

src/lib/fiat-curency/saving.ts
src/lib/i18n/saving.ts
src/lib/popup-mode/index.ts
src/lib/taquito-fast-rpc.ts
src/lib/temple/back/vault.ts
src/lib/temple/front/local-storage.ts
src/lib/temple/front/sync-tokens.ts
src/lib/ui/useLockUp.ts

https://www.notion.so/madfissolutions/Matvey-s-bug-error-Failed-to-execute-salitem-on-Storage-on-the-Swap-page-3cedaaca9002496b91c5a4d05c1dbf08

LocalStorage quota guards

---

src/app/ConfirmPage.tsx
src/app/templates/ExpensesView/ExpensesView.module.css
src/app/templates/ExpensesView/ExpensesView.tsx
src/app/templates/InternalConfirmation.tsx
src/app/templates/OperationView.tsx
src/app/templates/OperationsBanner.tsx

https://www.notion.so/madfissolutions/Add-the-opportunity-to-display-error-log-f354ade3f61045149c8242221d6b1988

Added collapse to copy error on confirmation

---

package.json
src/app/templates/SwapForm/SwapForm.tsx
src/lib/swap-router/components/DexTypeIcon/DexTypeIcon.tsx
src/lib/swap-router/config.ts
yarn.lock

- https://www.notion.so/madfissolutions/Development-05abe2b65cd14ae39a101533bc01b708?p=33267a862cd44361bdcf211657a1013b
- https://www.notion.so/madfissolutions/Development-05abe2b65cd14ae39a101533bc01b708?p=4a477fbca6fc466bbd15ca6810b9e270
- https://www.notion.so/madfissolutions/Development-05abe2b65cd14ae39a101533bc01b708?p=ec22bec216f74ff19d082ecd009c5585

Plenty Stable Swap and Ctez pools + Vortex DOGA/TEZ

---

src/app/atoms/SeedPhraseInput.tsx
src/app/atoms/SeedWordInput.tsx
src/app/pages/ImportAccount.tsx
src/app/pages/NewWallet/import/ImportFromSeedPhrase.tsx

https://www.notion.so/madfissolutions/Development-05abe2b65cd14ae39a101533bc01b708?p=85ebe7ba71504bb0a8da4fad8184b0bb

Settings import account from seed phrase input improvement

---

package.json
src/app/pages/ImportAccount.tsx
src/lib/temple/front/tzdns.ts
src/lib/temple/front/validate-delegate.ts
yarn.lock

https://www.notion.so/madfissolutions/Update-TezosDomainResolver-package-053db39019864da2a1697f80d87b96ad

Upgrade tez domains

---

src/lib/temple/back/dapp.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-91

TW-91: Sign payload parsing fix

---

src/lib/temple/networks.ts
src/lib/temple/types.ts

networks:
- Katmandu
- Monday net
- Daily net

TW-104: added new test networks

---

src/contentScript.ts
src/lib/temple/back/actions.ts
src/lib/temple/back/main.ts
src/lib/temple/beacon.ts
src/lib/temple/types.ts

added acknowledge message, #711 improvement

TW-220: beacon connection improvement

---

src/lib/notifications/components/bell.tsx
src/lib/notifications/components/item/content.tsx
src/lib/notifications/components/item/index.tsx
src/lib/notifications/components/notifications/index.tsx
src/lib/notifications/components/notifications/preview-item.tsx
src/lib/notifications/components/settings.tsx
src/lib/notifications/index.ts

- notification screens added
- t fix
- root state mock added
- props style fixed
- lint fix
- review fixes
- TW-331: Notifications. Refactor

TW-331: Notifications. Refactor

---

src/app/pages/AddAsset.tsx
src/app/templates/AssetIcon.tsx
src/app/templates/AssetInfo.tsx
src/lib/image-uri.ts
src/lib/ui/Image.tsx

- TW-427: Data URI for assets' icons. Support at add asset
- TW-427: Data URI for assets' icons. Support at displaying icons

TW-427: Data URI for assets' icons

---

src/app/pages/AddAsset/AddAsset.tsx

TW-571 Fix errors not being properly reset in AddAsset form

---

src/lib/apis/tzkt/api.ts
src/lib/temple/front/blockexplorer.ts
src/lib/temple/networks.ts
src/lib/temple/types.ts

TW-640 + TW-642 Remove legacy networks from default list; Add mumbainet

---

src/lib/temple/front/assets.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-641

TW-641 The swap section is not sorted by dollar value

---

src/lib/route3/constants.ts

TW-677 Change hardcoded token information

---

e2e/package.json
e2e/src/features/delegate.feature
e2e/src/features/send.feature
src/lib/temple/front/use-total-balance.hook.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-686

TW-686 Wrong total Tezos balance displayed if fiat is not USD

---

src/lib/apis/route3/fetch-route3-swap-params.ts
src/lib/apis/route3/route3.api.ts
src/lib/route3/constants.ts
src/lib/route3/interfaces/index.ts
src/lib/route3/utils/map-to-route3-hops.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-681

TW-681 Migration to 3Route v3

---

e2e/package.json
e2e/src/features/delegate.feature
e2e/src/features/send.feature
public/_locales/de/messages.json
public/_locales/en/messages.json
public/_locales/en_GB/messages.json
public/_locales/fr/messages.json
public/_locales/ja/messages.json
public/_locales/ko/messages.json
public/_locales/pt/messages.json
public/_locales/tr/messages.json
public/_locales/uk/messages.json
public/_locales/zh_CN/messages.json
public/_locales/zh_TW/messages.json
src/app/atoms/ABContainer.tsx

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-512

TW-512 Remove dot from "Copied" message

---

e2e/package.json
e2e/src/features/delegate.feature
e2e/src/features/send.feature
src/app/atoms/PageTitle.tsx
src/app/layouts/TabsPageLayout.tsx
src/app/pages/Receive/Receive.tsx
src/app/pages/Send.tsx
src/app/pages/Swap/Swap.tsx

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-504

TW-504 Different size of header text

---

src/app/hooks/use-metadata-loading.ts
src/app/store/tokens-metadata/actions.ts
src/app/store/tokens-metadata/epics.ts
src/app/store/tokens-metadata/reducers.ts
src/app/store/tokens-metadata/utils.ts
src/lib/assets/known-tokens.ts
src/lib/metadata/fetch.ts
src/lib/route3/constants.ts
src/lib/temple/networks.ts

https://madfish.atlassian.net/browse/TW-728

TW-728: Deprecated TKEY

---

e2e/src/features/delegate.feature
e2e/src/features/send.feature
package.json

Fix hotfix conflicts in development

---

package.json

Release 1.17.4 changes

---

package.json

version bump to 1.17.4

---

package.json
src/lib/temple/back/analytics.ts
yarn.lock

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-911

TW-911 Hide Jitsu source ip

---

src/app/layouts/PageLayout/Header/AccountDropdown/index.tsx
src/app/layouts/PageLayout/Header/NetworkSelect/index.tsx

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-918

TW-918 UX improvement for network and account changes

---

src/lib/apis/temple/metadata.ts
src/lib/apis/tzkt/api.ts
src/lib/temple/front/blockexplorer.ts
src/lib/temple/networks.ts
src/lib/temple/types.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-938

TW-938 Delete Mumbainet Testnet from networks

---

src/app/layouts/PageLayout/OnRampOverlay/OnRampOverlay.tsx

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-884

TW-884 Show Wert banner after onboarding

---

src/app/pages/Home/OtherComponents/MainBanner.tsx

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-735

TW-735: Asset balance value styles fix

---

package.json

Bump version to 1.18.2

---

public/_locales/en/messages.json
src/app/templates/SwapForm/SwapForm.tsx
src/app/templates/SwapForm/SwapFormInput/SwapFormInput.props.ts
src/app/templates/SwapForm/SwapFormInput/SwapFormInput.tsx

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1079

TW-1079: Change empty state text on swap input asset dropdown

---

src/lib/temple/networks.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1080

TW-1080: Change Temple and Ghostnet rpc urls

---

public/_locales/en/messages.json
src/app/ConfirmPage/confirm-dapp-form.tsx
src/app/templates/operation-view-layout.tsx

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1699

TW-1669: [Tezos] Mint / Deploy / Transfer NFT confirmations

---

package.json
src/app/atoms/NetworkSelectButton.tsx
src/app/pages/Home/OtherComponents/Tokens/components/AddTokenModal/index.tsx
src/app/pages/Send/hooks/use-evm-estimation-data.ts
src/app/templates/TransactionTabs/tabs/advanced.tsx
src/app/templates/TransactionTabs/tabs/details.tsx
src/app/templates/TransactionTabs/tabs/error.tsx
src/app/templates/TransactionTabs/tabs/fee.tsx
src/app/templates/operation-view-layout.tsx
src/lib/abi/opensea.ts
src/lib/abi/rarible.ts
src/lib/evm/on-chain/metadata.ts
src/lib/evm/on-chain/transactions/get-operation-kind.ts
src/lib/images-uri.ts
src/lib/temple/back/evm-dapp/handlers.ts
src/lib/temple/back/evm-dapp/utils.ts
src/lib/temple/back/evm-validation-schemas/index.ts
src/temple/evm/estimate.ts
src/temple/evm/web3-provider.ts
src/temple/front/chains.ts
yarn.lock

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1700

TW-1700: [EVM] Deploy / Mint / Approve / Transfer NFT confirmations

---

src/app/pages/Home/OtherComponents/Tokens/components/ListItem.tsx
src/lib/assets/hooks/tokens.ts
src/lib/assets/known-tokens.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1732

TW-1732: Clean up tezos default tokens

---

src/lib/analytics/use-analytics.hook.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1736

TW-1736: Add "beta" property for all analytic events

---

src/app/atoms/Checkbox.tsx
src/app/atoms/SettingsCheckbox.tsx
src/app/templates/CreatePasswordForm/index.tsx
src/app/templates/SecuritySettings/usage-analytics-settings.tsx
src/app/templates/enabling-setting.tsx
src/lib/temple/back/actions.ts
src/lib/temple/back/main.ts
src/lib/temple/back/vault/index.ts
src/lib/temple/front/client.ts
src/lib/temple/types.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1737

TW-1737: Gather beta testers addresses

---

yarn.lock

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1759

TW-1759: Update high vulnerability package

---

src/app/pages/Collectibles/CollectiblesTab/components/evm-meta-loading.ts
src/app/root-hooks/evm/balances-loading.ts
src/app/root-hooks/evm/tokens-metadata-loading.ts
src/app/root-hooks/evm/use-refresh-if-active.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1766

TW-1766: General bug fixes

---

src/app/layouts/PageLayout/OnRampOverlay/OnRampOverlay.tsx
src/app/layouts/PageLayout/OnRampOverlay/OnRampSmileButton/OnRampSmileButton.tsx
src/app/layouts/PageLayout/OnRampOverlay/utils/getWertLink.util.ts
src/app/pages/Home/Home.tsx
yarn.lock

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1770

TW-1770: Wert top-up session id

---

src/lib/temple/chains-specs.ts
src/temple/networks.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1777

TW-1777: Rename 'Ether' tokens to 'Ethereum'

---

public/_locales/en/messages.json
src/app/layouts/PageLayout/NewsletterOverlay/NewsletterOverlay.tsx
src/app/layouts/PageLayout/OnRampOverlay/OnRampOverlay.tsx
src/app/layouts/PageLayout/OnRampOverlay/OnRampSmileButton/OnRampSmileButton.tsx
src/app/layouts/PageLayout/OnRampOverlay/utils/getWertLink.util.ts
src/app/layouts/PageLayout/ReactivateAdsOverlay/index.tsx
src/app/pages/EarnTez/modals/delegation/confirm-delegation-content.tsx
src/app/pages/Send/context.ts
src/app/pages/Send/form/BaseForm.tsx
src/app/pages/Send/form/EvmForm.tsx
src/app/pages/Send/form/TezosForm.tsx
src/app/pages/Send/index.tsx
src/app/pages/Swap/form/index.tsx
src/app/store/index.ts
src/app/store/migrations.ts
src/app/store/settings/actions.ts
src/app/store/settings/reducers.ts
src/app/store/settings/selectors.ts
src/app/store/settings/state.mock.ts
src/app/store/settings/state.ts
src/app/templates/CreatePasswordForm/index.tsx
src/app/templates/InternalConfirmation.tsx
src/lib/apis/wert.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1730

TW-1730: Expand tokens top-up with Wert modal

---

.github/workflows/code-quality.yml
public/_locales/en/messages.json
src/app/ConfirmPage/hooks/use-is-browser-fullscreen.ts
src/app/ConfirmPage/index.tsx
src/app/atoms/PageModal/index.tsx
src/app/pages/EarnTez/components/earn-operation-modal.tsx
src/app/pages/EarnTez/modals/finalize/index.tsx
src/app/pages/Send/form/TezosForm.tsx
src/app/pages/Send/hooks/use-tezos-estimation-data.ts
src/app/pages/Send/modals/ConfirmSend/EvmContent.tsx
src/app/pages/Send/modals/ConfirmSend/TezosContent.tsx
src/app/pages/Send/modals/ConfirmSend/index.tsx
src/app/pages/Send/utils.ts
src/app/pages/Swap/modals/ConfirmSwap/TezosContent.tsx
src/app/pages/Token/AssetBanner.tsx
src/app/templates/Balance.tsx
src/app/templates/CreatePasswordForm/index.tsx
src/app/templates/one-asset-header.tsx
src/app/toaster.tsx
src/lib/ui/show-tx-submit-toast.util.ts
src/temple/front/use-block-explorers.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1778

TW-1778: Minor fixes (part 4)

---

src/app/templates/AssetImage/AssetImageStacked.tsx
src/app/templates/activity/ActivityItem/ActivityOperationBase/index.tsx
src/content-scripts/main.ts
src/lib/temple/back/actions.ts
src/lib/temple/back/dapp.ts
src/lib/temple/back/main.ts
src/lib/temple/front/client.ts
src/lib/temple/front/lock.ts
src/lib/ui/use-images-stack-loading.ts
src/lib/utils/are-string-arrays-equal.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1821

TW-1821: Release fixes

---

src/app/hooks/use-accounts-initialized-sync.ts
src/app/pages/Swap/modals/ConfirmSwap/EvmContent.tsx
src/app/store/migrations.ts
src/app/store/tezos/balances/utils.ts
src/app/templates/buy-modals/crypto-exchange-modal/steps/OrderCreation/components/FormContent.tsx
src/lib/temple/back/vault/migrations.ts

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1830

TW-1830: Crash after migration with custom networks

---

src/app/ConfirmPage/evm-confirm-dapp-form.tsx
src/app/ConfirmPage/hooks/use-track-dapp-interaction.ts
src/app/ConfirmPage/tezos-confirm-dapp-form.tsx

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1789

TW-1789: Analytics for DApp interactions

---

src/app/atoms/TagButton.tsx
src/app/pages/Home/OtherComponents/Tokens/components/EvmChainTokensTab.tsx
src/app/pages/Home/OtherComponents/Tokens/components/EvmTokensTab.tsx
src/app/pages/Home/OtherComponents/Tokens/components/MultiChainTokensTab.tsx
src/app/pages/Home/OtherComponents/Tokens/components/TokenTag/ApyTag.tsx
src/app/pages/Home/OtherComponents/Tokens/components/TokenTag/DelegateTag.tsx
src/app/pages/Home/OtherComponents/Tokens/components/TokenTag/EvmIncentiveTag.tsx
src/app/templates/TokenListItem.tsx

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1859

TW-1859:  Badge for Etherlink USDC

---

src/app/templates/CreatePasswordForm/index.tsx

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1907

TW-1907 fix bug when advertising was disabled after account register

---

package.json
src/app/templates/DAppConnection/index.tsx
src/lib/apis/tzkt/misc.ts
src/lib/temple/back/dapp.ts
src/lib/temple/chains-specs.ts
src/lib/temple/types.ts
src/temple/front/use-block-explorers.ts
src/temple/networks.ts
yarn.lock

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-1915

TW-1915 add shadownet as predefined testnet
